// Maps the string icon names stored on NodeTypeDefinition/WorkflowNodeData (they
// have to be plain strings, not component references, since node data is
// persisted as JSON) to actual lucide-react components for rendering in the
// palette and on canvas nodes.
import {
  AudioLines,
  Binary,
  Bot,
  Clapperboard,
  Clock,
  Code,
  Copy,
  Database,
  Filter,
  FileDiff,
  FilePen,
  FilePlus,
  FileText,
  Film,
  FolderInput,
  GitBranch,
  Globe,
  HelpCircle,
  Image as ImageIcon,
  Info,
  List,
  Merge,
  MessageSquare,
  Network,
  Pause,
  Play,
  Rocket,
  Scissors,
  Search,
  Send,
  Square,
  Tags,
  Trash2,
  Undo2,
  Upload,
  Webhook,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const NODE_ICONS: Record<string, LucideIcon> = {
  Play,
  Webhook,
  Clock,
  Database,
  MessageSquare,
  Bot,
  Globe,
  Code,
  List,
  FileText,
  FileDiff,
  FilePen,
  FilePlus,
  Trash2,
  FolderInput,
  Copy,
  Undo2,
  Rocket,
  Filter,
  GitBranch,
  Merge,
  Scissors,
  Tags,
  Binary,
  Upload,
  Search,
  ImageIcon,
  Clapperboard,
  Film,
  AudioLines,
  Info,
  Square,
  Send,
  Wrench,
  Pause,
  Network,
};

export function getNodeIcon(name: string | undefined): LucideIcon {
  if (!name) return HelpCircle;
  return NODE_ICONS[name] ?? HelpCircle;
}
